name: Bug Report
description: File a bug report
title: "[🐛]: "
labels: ["bug"]
assignees:
  - grethler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: optional
    validations:
      required: false
  - type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
  attributes:
    label: Environment
    description: What environment are you using?
    multiple: false
    options:
      - Docker
      - Python virtual environment
      - Normal shell
    default: None
  validations:
    required: true
  - type: dropdown
  attributes:
    label: Operation System
    description: What OS are you using?
    multiple: false
    options:
      - Windows
      - Linux
      - MacOS
    default: None
  validations:
    required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
