name: Feature Request
description: File a feature request
title: "[🔨]: "
labels: ["enhancement"]
assignees:
  - grethler
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What should be implemented?
      placeholder: Tell us what you want.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
